# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRZ.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InphutData = QtWidgets.QTextEdit(self.centralwidget)
        self.InphutData.setGeometry(QtCore.QRect(213, 37, 501, 151))
        self.InphutData.setObjectName("InphutData")
        self.OutputText = QtWidgets.QTextBrowser(self.centralwidget)
        self.OutputText.setGeometry(QtCore.QRect(210, 310, 511, 61))
        self.OutputText.setObjectName("OutputText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 330, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.ButtonVNM = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonVNM.setGeometry(QtCore.QRect(210, 230, 131, 51))
        self.ButtonVNM.setObjectName("ButtonVNM")

        self.ButtonUSA = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonUSA.setGeometry(QtCore.QRect(340, 230, 131, 51))
        self.ButtonUSA.setObjectName("ButtonUSA")

        self.ButtonCAN = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonCAN.setGeometry(QtCore.QRect(470, 230, 131, 51))
        self.ButtonCAN.setObjectName("ButtonCAN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        self.menuDrop_VN = QtWidgets.QMenu(self.menubar)
        self.menuDrop_VN.setObjectName("menuDrop_VN")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDrop_VN.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Passport Number"))
        self.label_2.setText(_translate("MainWindow", "DOB (DD MM YY)"))
        self.label_3.setText(_translate("MainWindow", "EXP Day"))
        self.label_4.setText(_translate("MainWindow", "CMND/SSN/ ID num"))
        self.label_5.setText(_translate("MainWindow", "SEX"))
        self.label_6.setText(_translate("MainWindow", "Output"))
        self.ButtonVNM.setText(_translate("MainWindow", "VNM"))
        self.ButtonUSA.setText(_translate("MainWindow", "USA"))
        self.ButtonCAN.setText(_translate("MainWindow", "CAN"))
        self.menuDrop_VN.setTitle(_translate("MainWindow", "Drop VN"))

    def UI_ClassTest(self):
        print("file UI chay ok")
